// Generated by make-ip-conf.pl
// eth4 10.10.1.1 00:04:23:b7:12:66
// eth5 10.10.2.1 00:04:23:b7:12:67

// Shared IP input path and routing table
ip :: Strip(14)
    -> CheckIPHeader(INTERFACES 10.10.1.1/255.255.255.0 10.10.2.1/255.255.255.0)
    -> rt :: StaticIPLookup(
	10.10.1.1/32 0,
	10.10.1.255/32 0,
	10.10.1.0/32 0,
	10.10.2.1/32 0,
	10.10.2.255/32 0,
	10.10.2.0/32 0,
	10.10.1.0/255.255.255.0 1,
	10.10.2.0/255.255.255.0 2,
	255.255.255.255/32 0.0.0.0 0,
	0.0.0.0/32 0,
	10.10.1.2/255.255.255.255 10.10.1.2 1,
	10.10.2.2/255.255.255.255 10.10.2.2 2);

// ARP responses are copied to each ARPQuerier and the host.
arpt :: Tee(3);

// Input and output paths for eth4
c0 :: Classifier(12/0806 20/0001, 12/0806 20/0002, 12/0800, -);
FromDevice(eth4) -> c0;
out0 :: Queue(200) -> todevice0 :: ToDevice(eth4);
c0[0] -> ar0 :: ARPResponder(10.10.1.1 00:04:23:b7:12:66) -> out0;
arpq0 :: ARPQuerier(10.10.1.1, 00:04:23:b7:12:66) -> out0;
c0[1] -> arpt;
arpt[0] -> [1]arpq0;
c0[2] -> Paint(1) -> ip;
c0[3] -> Print("eth4 non-IP") -> Discard;

// Input and output paths for eth5
c1 :: Classifier(12/0806 20/0001, 12/0806 20/0002, 12/0800, -);
FromDevice(eth5) -> c1;
out1 :: Queue(200) -> todevice1 :: ToDevice(eth5);
c1[0] -> ar1 :: ARPResponder(10.10.2.1 00:04:23:b7:12:67) -> out1;
arpq1 :: ARPQuerier(10.10.2.1, 00:04:23:b7:12:67) -> out1;
c1[1] -> arpt;
arpt[1] -> [1]arpq1;
c1[2] -> Paint(2) -> ip;
c1[3] -> Print("eth5 non-IP") -> Discard;

// Local delivery
toh :: ToHost;
arpt[2] -> toh;
rt[0] -> EtherEncap(0x0800, 1:1:1:1:1:1, 2:2:2:2:2:2) -> toh;

// Forwarding path for eth4
rt[1] -> DropBroadcasts
    -> cp0 :: PaintTee(1)
    -> gio0 :: IPGWOptions(10.10.1.1)
    -> FixIPSrc(10.10.1.1)
    -> dt0 :: DecIPTTL
    -> fr0 :: IPFragmenter(1500)
    -> [0]arpq0;
dt0[1] -> ICMPError(10.10.1.1, timeexceeded) -> rt;
fr0[1] -> ICMPError(10.10.1.1, unreachable, needfrag) -> rt;
gio0[1] -> ICMPError(10.10.1.1, parameterproblem) -> rt;
cp0[1] -> ICMPError(10.10.1.1, redirect, host) -> rt;

// Forwarding path for eth5
rt[2] -> DropBroadcasts
    -> cp1 :: PaintTee(2)
    -> gio1 :: IPGWOptions(10.10.2.1)
    -> FixIPSrc(10.10.2.1)
    -> dt1 :: DecIPTTL
    -> fr1 :: IPFragmenter(1500)
    -> [0]arpq1;
dt1[1] -> ICMPError(10.10.2.1, timeexceeded) -> rt;
fr1[1] -> ICMPError(10.10.2.1, unreachable, needfrag) -> rt;
gio1[1] -> ICMPError(10.10.2.1, parameterproblem) -> rt;
cp1[1] -> ICMPError(10.10.2.1, redirect, host) -> rt;
